#!/usr/bin/env python3
"""Concatenate the markdown docs into a single llms-full.txt for LLM ingestion.

Pattern follows the llms.txt spec proposal: llms-full.txt is the entire body
of the docs as one markdown stream so an LLM can read the whole thing in a
single retrieval. Run from the repo root:

    python scripts/build_llms_full.py

Writes docs/llms-full.txt. Idempotent.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "llms-full.txt"

ORDER = [
    "index.md",
    "quickstart.md",
    "concepts.md",
    "integrations.md",
    "compliance.md",
    "cli.md",
]


def main() -> int:
    if not DOCS.exists():
        print(f"ERROR: {DOCS} does not exist", file=sys.stderr)
        return 1

    parts: list[str] = []
    parts.append("# ai-audit-trail — full documentation\n")
    parts.append(
        "This file is the concatenation of all documentation pages, intended "
        "for ingestion by LLM tools (Cursor `@docs`, Anthropic Skills, Context7, "
        "etc.). Generated by `scripts/build_llms_full.py`.\n"
    )

    for name in ORDER:
        path = DOCS / name
        if not path.exists():
            print(f"WARNING: missing doc page {path}", file=sys.stderr)
            continue
        parts.append("\n\n---\n\n")
        parts.append(f"<!-- source: docs/{name} -->\n")
        parts.append(path.read_text(encoding="utf-8"))

    OUT.write_text("\n".join(parts), encoding="utf-8")
    size_kb = OUT.stat().st_size / 1024
    print(f"Wrote {OUT.relative_to(ROOT)} ({size_kb:.1f} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
